### ISSUE TITLE
dicomsort does not launch on MacOS catalina 

### ISSUE THREAD

**Issue by mrj04** [dicomsort/dicomsort#125]
dicomsort
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/dicomsort", line 13, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/dicomsort", line 8, in main
    ds = DicomSort(0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dicomsort/gui/core.py", line 26, in __init__
    self.frame = MainFrame(None, -1, "DicomSort", size=(500, 500))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dicomsort/gui/core.py", line 45, in __init__
    self.Create()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dicomsort/gui/core.py", line 98, in Create
    self.selector = widgets.FieldSelector(self, titles=titles)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dicomsort/gui/widgets.py", line 434, in __init__
    self.create()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dicomsort/gui/widgets.py", line 506, in create
    self._initialize_layout()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dicomsort/gui/widgets.py", line 526, in _initialize_layout
    vboxOptions.Add(self.search, 0,
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at /Users/robind/projects/bb2/dist-osx-py39/build/ext/wxWidgets/src/common/sizer.cpp(2159) in DoInsert(): Horizontal alignment flags are ignored with wxEXPAND

**Comment by suever** [comment]
Thanks for the report @mrj04, this should be addressed in the [3.0.0 version of DICOM Sort](https://github.com/dicomsort/dicomsort/releases/tag/v3.0.0) that I just released. Do you mind giving it a try? I'll go ahead and close this but feel free to open a new ticket if you continue to have issues
