### ISSUE TITLE
AttributeError when deselecting default SeriesDescription from Properties to Use

### ISSUE THREAD

**Issue by tossin15** [dicomsort/dicomsort#170]
Hello,

I'm using the latest stable binaries from the website on Windows.

I'd like to sort a series without the SeriesDescription property.  However, when I press the deselect button (<<), I receive the following error in a pop-up window:

```
Traceback (most recent call last):

  File "\\VBoxSvr\dicomsort\dicomsort\gui\widgets.py", line 462, in DeselectItem

AttributeError: 'SeriesRemoveWarningDlg' object has no attribute 'choice'
```

As a separate issue, when pressing the "File Issue" button in the Error pop-up window, I get another error:

```
Traceback (most recent call last):

  File "\\VBoxSvr\dicomsort\dicomsort\gui\dialogs.py", line 115, in on_file

  File "\\VBoxSvr\dicomsort\dicomsort\gui\dialogs.py", line 74, in body

AttributeError: module 'os' has no attribute 'uname'
```

Copies of SeriesDescription can be added and removed from Properties to Use without problem, but the original will always call an error.

**Comment by suever** [comment]
Thanks for reporting these, they are likely due to recent upgrades to WxPython. I'll get a fix out soon! Sorry about that

**Comment by FahadAldhway** [comment]
anyupdate about this issue
